[colors]
# base colors
background = "black"
foreground = "white"
highlight = "cyan"
error = "red"

[layout]
padding = 1
margin = 1
border_style = "solid"

[fonts]
regular = "monospace"
bold = "monospace bold"

[animations]
enable = true

[username_field]
remember = true

[username_field.style]
show_title = true
title = "Umsername!"
title_color = "white"
content_color = "white"
title_color_focused = "light cyan"
content_color_focused = "light cyan"
show_border = true
border_color = "white"
border_color_focused = "light cyan"
use_max_width = true
max_width = 48

[password_field]
content_replacement_character = "*"

[password_field.style]
show_title = true
title = "Pamsmword! (shhh, secret :3)"
title_color = "white"
content_color = "white"
title_color_focused = "light magenta"
content_color_focused = "light magenta"
show_border = true
border_color = "white"
border_color_focused = "light magenta"
use_max_width = true
max_width = 48

[environment_switcher]
switcher_visibility = "visible"
toggle_hint = "Switcher %key%"
toggle_hint_color = "dark gray"
toggle_hint_modifiers = ""
include_tty_shell = false
remember = true
show_movers = true
mover_color = "dark gray"
mover_modifiers = ""
mover_color_focused = "light yellow"
mover_modifiers_focused = "bold"
left_mover = "<"
right_mover = ">"
mover_margin = 1
show_neighbours = true
neighbour_color = "dark gray"
neighbour_modifiers = ""
neighbour_color_focused = "light blue"
neighbour_modifiers_focused = ""
neighbour_margin = 1
selected_color = "gray"
selected_modifiers = "underlined"
selected_color_focused = "light green"
selected_modifiers_focused = "bold"
max_display_length = 8
no_envs_text = "No environments..."
no_envs_color = "white"
no_envs_modifiers = ""
no_envs_color_focused = "red"
no_envs_modifiers_focused = ""

